DELETE http://localhost:3003/api/blogs/66a8eb7102774da60eb8d0ab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXIiLCJpZCI6IjY2YTllZGFmNzI2OWZhNzU5Y2RhZjEwNyIsImlhdCI6MTcyMjQxMjQ5NX0.8oq1AnJ_S_D7kMRDqAYqNOVW0rFT6369jDuJRwVmgYA